### ISSUE TITLE
Concreteness fading - specific examples

### ISSUE THREAD

**Issue by lidavidm** [lidavidm/cs6360#1]
- Instead of `this`, show a picture of what the object is (e.g. the robot)
- Colors/backgrounds represent:
  - Different fields?
  - Type/interfaces?
- Methods in OOP were originally conceived of as 'message passing' (as in Smalltalk/Objective-C). We could emphasize this by requiring method invocation pass through a 'tell' block like 'tell (picture of robot) move forward'
  - Going with the blueprint metaphor below, the messages/methods that are available could be grouped by class/interface. For instance, there'd be a blueprinty-looking toolbox with all the methods for a particular class. There'd be a blueprint with all the methods in an interface. Color-coding or pattern-matching could help hint which are compatible with which.
- We could _literally_ show boxing in Java, though maybe that's a mechanic we don't care about? (It could be interesting in that we could have a "box" block that converts a primitive type to an object type)
- Instance variables, member variables - ?
- Class object (vs the instance) - blueprint block? (a block that looks like a blueprint with the picture of the object inside) (== `getClass()` method)
- Inheritance - ?
- Encapsulation - ?
- Class definitions - ? (could work well with the blueprint metaphor)
  - Encapsulation: the blueprints you make are fully unrolled, and you can see everything. The blueprints others make are rolled up, hiding the section for instance variables
- Justify some changes as software engineering principles
  - Factory worker complaining that blueprint names don't make any sense
  - Give them an interface or existing inheritance relationship, and force them to manually change the  
- Good late game challenge: robot gets EMPed by the enemy, you have to SSH in and write Java code directly.
- Sample for adding first methods: player goes to inspect robot for first time, realizes that they don't have getters and setters. have to implement before continuing.
- Leveling up a robot's abilities (methods) allows access to info like return type and parameters

We can justify fading to the player by saying they are getting more direct control, and thus have more capabilities, at the cost of having less of a visual metaphor.

How quickly do we want to fade? We can't quite fade everything at once. DragonBox faded things in and out, which is trickier. But having things at different levels of fading may be confusing. One idea: once methods are introduced, have some methods be "low level". Implementing them means that your tools are partially or fully faded.

Having good animations/art matters - e.g. when we introduce the blueprint block, zooming in and showing that it is an actual blueprint before dropping it into the toolbox might help reinforce what it's meant to represent.

**Comment by michaelmauer** [comment]
* Justify some changes as software engineering principles
  * Factory worker complaining that blueprint names don't make any sense
  * Give them an interface or existing inheritance relationship, and force them to manually change the  
* Good late game challenge: robot gets EMPed by the enemy, you have to SSH in and write Java code directly.
