### ISSUE TITLE
Pretest and posttest

### ISSUE THREAD

**Issue by lidavidm** [lidavidm/cs6360#37]
- [x] Write questions
- [x] UUID
- [x] Server side component
- [x] Test with students
- [x] Log answers
- [x] Integrate into UI

**Comment by monozuki** [comment]
https://docs.google.com/document/d/1Z25OHON29EBBeH9xLCKbOMjWa0s-8DHdSxOgtaovniM/edit
Put a couple of ideas for questions in a google doc^

All of them so far are centered around example code, which is a little cumbersome. Also, it probably wouldn't be helpful in this context to ask about things like OO terminology.
And I'm guessing eventually we want to format these as multiple choice questions?

**Comment by lidavidm** [comment]
We should label the pretest "Robot Commander Aptitude Test" and the post-test "Robot Commander Proficiency Test" and integrate it all into the game.

**Comment by michaelmauer** [comment]
This is genius. Definitely have to do it this way.

**Comment by lidavidm** [comment]
So Andersen said 5 questions is probably the most we want - that means we should focus on our late-game concepts to maximize value.
